version: "3.9"
services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    stdin_open: true
    tty: true
    command:
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_SSLEMAIL?Variable not set}
    labels:
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.enable=true"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.middlewares=oauth"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"

  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      PROVIDERS_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      PROVIDERS_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET: ${SECRET}
      COOKIE_DOMAIN: ${DOMAIN}
      AUTH_HOST: oauth.${DOMAIN}
    labels:
      traefik.http.middlewares.oauth.forwardauth.address: http://oauth:4181
      traefik.http.middlewares.oauth.forwardauth.authResponseHeaders: X-Forwarded-User
      traefik.http.middlewares.oauth.forwardauth.trustForwardHeader: "true"
      traefik.http.routers.oauth.middlewares: oauth
      traefik.enable: "true"
      traefik.http.routers.oauth.rule: Host(`oauth.${DOMAIN}`)
      traefik.http.routers.oauth.tls: "true"
      traefik.http.routers.oauth.tls.certresolver: letsencrypt
      traefik.http.services.oauth.loadbalancer.server.port: 4181

networks:
  default:
    name: traefik

